from enum import Enum

Usage = Enum("Usage", ["SINGLE_CELL", "MULTI_CELL"])

### WARNING: DO NOT EDIT THIS FILE ABOVE THIS LINE! ###

usage = Usage.SINGLE_CELL
extract_traces = True
acquisition_frequency = 100
pacing_frequency = 1
apply_photo_bleach_correction = True
beginning_frames_removed = 1
max_pacing_deviation = 0.2
good_snr = False
quiet = True

# videos_directory = "E:/06-12-2023_PGP1WT-RGECO-aActGFP_PFRPMI_afi_acute/dmso"
videos_directory = "D:/30-11-20 ISO WT/3um"
